MODEL:
  TYPE: generalized_wsl
  CONV_BODY: FPN.add_fpn_ResNet18_conv5_body
  NUM_CLASSES: 21
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  MAX_ITER: 36000
  STEPS: [0, 24000, 32000]
  WARM_UP_ITERS: 0
RESNETS:
  RES5_DILATION: 1
  TRANS_FUNC: 'residual_transformation'
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: wsl_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: models/DRN-WSOD/resnet18_model_120.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val')
  PROPOSAL_FILES: ('detectron/datasets/data/proposals/mcg_voc_2007_train.pkl', 'detectron/datasets/data/proposals/mcg_voc_2007_val.pkl')
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_AT: 2
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('voc_2007_test',)
  PROPOSAL_FILES: ('detectron/datasets/data/proposals/mcg_voc_2007_test.pkl',)
  PROPOSAL_LIMIT: 2048
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.000000001
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'ID'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 11
WSL:
  WSL_ON: True
  ITER_SIZE: 1
  MEAN_LOSS: True
  DILATION: 2
MEMONGER: True
VIS: True
VIS_TH: 0.1
USE_NCCL: True
DEDUP_BOXES: 0.0625
